# Generated by Django 5.1.5 on 2025-06-04 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_alter_ticket_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activity.ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.FileField(upload_to='media/tickets/'),
        ),
    ]
